### ISSUE TITLE
androidMainfest오류남니다

### ISSUE THREAD

**Issue by qwsd1109** [DSM-Undefined/Hang-Man_Android#26]
androidMainfest에서 
"
>>>>>>> Stashed changes
=======
<<<<<<< Updated upstream
        <activity android:name=".ui.activity.GameroomActivity" />
" 등이 있으므로 삭제해주시길바랍니다.

**Comment by qwsd1109** [comment]
어라 마크다운 이었네

**Comment by KRMKGOLD** [comment]
ㅋㅋㅋㅋㅋㅋㅋ 그거 `>>>>>>>` 때문에 그런듯
매니패스트 그냥 마스터에서 수정해도 되요?

**Comment by qwsd1109** [comment]
넵 저는 일단 수정했습니다

**Comment by KRMKGOLD** [comment]
마스터에 수정되었으니까 신경 안쓰고 이슈 닫을게요
